version: "3.5"

services:
    db:
        build:
            context: .
        image: kozin/postgres
        container_name: postgres_db
        restart: on-failure
        networks:
            - db_network
        environment:
            POSTGRES_PASSWORD: "pass"
        volumes:
            - /db_data:/var/lib/postgresql/data

networks:
    db_network:
        name: db_network
