version: '3'

services:
    db:
        build:
            context: .
        image: kozin/postgres
        container_name: postgres_db
        restart: on-failure
        network_mode: "host"
        environment:
            POSTGRES_PASSWORD: "pass"
        volumes:
            - /db_data:/var/lib/postgresql/data
            
